mode = "light"

accent = "#644AC9"
selection = "#CFCFDE"
selection_foreground = "#1F1F1F"
muted = "#6C664B"

background = "#FFFBEB"
dark_background = "#ECE9DF"
darker_background = "#DEDCCF"
lighter_background = "#EFEDDC"

foreground = "#1F1F1F"
dark_foreground = "#6C664B"
light_foreground = "#2C2B31"
bright_foreground = "#2C2B31"

red = "#CB3A2A"
yellow = "#846E15"
orange = "#A34D14"
green = "#14710A"
cyan = "#036A96"
blue = "#644AC9"
magenta = "#A3144D"
brown = "#52270A"

bright_red = "#D74C3D"
bright_yellow = "#9E841A"
bright_green = "#198D0C"
bright_cyan = "#047FB4"
bright_blue = "#7862D0"
bright_magenta = "#BF185A"
